//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleGame {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleGame.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ......................................................................................................................................................
        ///......................................................................................................................................................
        ///......................................................................................................................................................
        ///........................................................ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Level_1 {
            get {
                return ResourceManager.GetString("Level_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ...♥..............................................................................................................................................♥...
        ///...♥..............................................................................................................................................♥...
        ///...♥..............................................................................................................................................♥...
        ///...♥.................................................... [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _███_
        ///?███?
        ///??█??
        ///█████
        ///█?█?█
        ///█?█?█
        ///??█??
        ///?███?
        ///██?██
        ///?????
        ///?????.
        /// </summary>
        internal static string PlayerJump {
            get {
                return ResourceManager.GetString("PlayerJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _███_
        ///?███?
        ///??█??
        ///█████
        ///█?█?█
        ///█?█?█
        ///??█??
        ///?███?
        ///?█?█?
        ///?█?█?
        ///██?██.
        /// </summary>
        internal static string PlayerRunLeft1 {
            get {
                return ResourceManager.GetString("PlayerRunLeft1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _███_
        ///?███?
        ///??█??
        ///█████
        ///█?█?█
        ///█?█?█
        ///??█??
        ///?███?
        ///██?█?
        ///???█?
        ///???██.
        /// </summary>
        internal static string PlayerRunLeft2 {
            get {
                return ResourceManager.GetString("PlayerRunLeft2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _███_
        ///?███?
        ///??█??
        ///█████
        ///█?█?█
        ///█?█?█
        ///??█??
        ///?███?
        ///?█?█?
        ///?█?█?
        ///██?██.
        /// </summary>
        internal static string PlayerRunLeft3 {
            get {
                return ResourceManager.GetString("PlayerRunLeft3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _███_
        ///?███?
        ///??█??
        ///█████
        ///█?█?█
        ///█?█?█
        ///??█??
        ///?███?
        ///?█?██
        ///?█???
        ///██???.
        /// </summary>
        internal static string PlayerRunLeft4 {
            get {
                return ResourceManager.GetString("PlayerRunLeft4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _███_
        ///?███?
        ///??█??
        ///█████
        ///█?█?█
        ///█?█?█
        ///??█??
        ///?███?
        ///?█?█?
        ///?█?█?
        ///██?██.
        /// </summary>
        internal static string PlayerRunRight1 {
            get {
                return ResourceManager.GetString("PlayerRunRight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _███_
        ///?███?
        ///??█??
        ///█████
        ///█?█?█
        ///█?█?█
        ///??█??
        ///?███?
        ///?█?██
        ///?█???
        ///██???.
        /// </summary>
        internal static string PlayerRunRight2 {
            get {
                return ResourceManager.GetString("PlayerRunRight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _███_
        ///?███?
        ///??█??
        ///█████
        ///█?█?█
        ///█?█?█
        ///??█??
        ///?███?
        ///?█?█?
        ///?█?█?
        ///██?██.
        /// </summary>
        internal static string PlayerRunRight3 {
            get {
                return ResourceManager.GetString("PlayerRunRight3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _███_
        ///?███?
        ///??█??
        ///█████
        ///█?█?█
        ///█?█?█
        ///??█??
        ///?███?
        ///██?█?
        ///???█?
        ///???██.
        /// </summary>
        internal static string PlayerRunRight4 {
            get {
                return ResourceManager.GetString("PlayerRunRight4", resourceCulture);
            }
        }
    }
}
